<?php
require_once 'includes/access.php'; require_page_access(); require 'includes/layout.php';
page_start('Reports');

$types = [
    ['Casualty Report',           'Comprehensive report of all casualties by barangay and severity'],
    ['Evacuation Report',         'Evacuation center occupancy and household distribution'],
    ['Vehicle Request Report',    'Summary of all vehicle requests and logistics operations'],
    ['Relief Distribution Report','Inventory and distribution tracking across all barangays'],
    ['Damage Assessment Report',  'Verified damage assessments and household impact analysis'],
    ['Overall Summary Report',    'Complete disaster response overview with all metrics'],
];

$recent = [
    ['Daily Casualty Report',     '2026-05-01', 'Juan Dela Cruz', 'PDF'],
    ['Weekly Relief Distribution','2026-04-30', 'Maria Santos',   'Excel'],
    ['Evacuation Center Status',  '2026-04-29', 'Juan Dela Cruz', 'PDF'],
];
?>

<div class="page-head">
    <h1 class="page-title">Reports & Summaries</h1>
</div>

<div class="grid g4">
    <?php foreach([['1,247', 'Total Households', '+45'], ['89', 'Total Casualties', '+12'], ['156', 'Relief Distributions', '+23'], ['78', 'Vehicle Requests', '+8']] as $s): ?>
        <div class="card">
            <div class="mini"><?=$s[0]?></div>
            <div class="report-stat-value"><?=$s[1]?></div>
            <span class="badge b-green"><?=$s[2]?> today</span>
        </div>
    <?php endforeach; ?>
</div>

<div class="card mt">
    <h2>Generate Report</h2>
    <div class="grid g3">
        <?php foreach($types as $t): ?>
            <div class="card report-type-card">
                <div class="report-type-icon">▤</div>
                <h3><?=$t[0]?></h3>
                <p class="mini"><?=$t[1]?></p>
                <button class="btn btn-primary btn-block" onclick="alert('Generating <?=$t[0]?>...')">Generate</button>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<div class="card mt">
    <h2>Recent Reports</h2>
    <div class="table-wrap">
        <table class="table">
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Date Generated</th>
                    <th>Generated By</th>
                    <th>Type</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($recent as $r): ?>
                    <tr>
                        <td><?=$r[0]?></td>
                        <td><?=$r[1]?></td>
                        <td><?=$r[2]?></td>
                        <td><?=status_badge($r[3])?></td>
                        <td class="actions">
                            <button class="btn btn-light">Download</button>
                            <button class="btn btn-light">Print</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="card mt">
    <h2>Export Options</h2>
    <div class="actions">
        <button class="btn btn-danger">Export PDF</button>
        <button class="btn btn-success">Export Excel</button>
        <button class="btn btn-light" onclick="window.print()">Print Report</button>
    </div>
</div>

<?php page_end(); ?>
