-- ============================================================================
-- PDERALSS · Vehicle Requests
-- Run this once in the Supabase dashboard -> SQL Editor.
-- (The app also creates this table automatically on first page load if it
--  does not exist, using the same definition.)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.vehicle_requests (
    request_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code     VARCHAR(20) UNIQUE,                 -- e.g. VR-2026-084
    barangay         VARCHAR(100) NOT NULL,              -- copied from the social worker's users.address
    purpose          VARCHAR(60)  NOT NULL,
    passengers       INTEGER      NOT NULL CHECK (passengers >= 0),
    urgency          VARCHAR(10)  NOT NULL CHECK (urgency IN ('High','Medium','Low')),
    requested_date   DATE         NOT NULL,
    notes            TEXT,
    status           VARCHAR(12)  NOT NULL DEFAULT 'Pending'
                     CHECK (status IN ('Pending','Approved','Scheduled','Completed','Rejected')),
    assigned_vehicle VARCHAR(100),
    requested_by     VARCHAR(50)  NOT NULL,              -- users.user_id of the social worker
    reviewed_by      VARCHAR(50),                        -- users.user_id of the MDRRMO officer
    reviewed_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vehicle_requests_requested_by ON public.vehicle_requests (requested_by);
CREATE INDEX IF NOT EXISTS idx_vehicle_requests_status       ON public.vehicle_requests (status);
CREATE INDEX IF NOT EXISTS idx_vehicle_requests_date         ON public.vehicle_requests (requested_date);

-- The PHP app connects directly as the database owner, which bypasses RLS.
-- Turning RLS on (with no policies) blocks anonymous access through Supabase's
-- auto-generated REST API, so this table is only reachable through your app.
ALTER TABLE public.vehicle_requests ENABLE ROW LEVEL SECURITY;
